### ISSUE TITLE
Enable compression level for fastq files during bclconvert

### ISSUE THREAD

**Issue by xiamaz** [LaborBerlin/hum-dragen-routine#19]
Currently generated fastq files have compression level 1, this seems low and should be fixed in bclconvert step.

**Comment by your-highness** [comment]
This was already done via [6ab82d8](https://github.com/LaborBerlin/hum-dragen-routine/commit/6ab82d872e83808df572df64fa787dd54e543ce8)

We need to work on compression of DRAGEN germline output though

**Comment by xiamaz** [comment]
Compression output in germline is also set to BEST_COMPRESSION in our files, I confirmed that in the latest run log.
