### ISSUE TITLE
Generate Report for pedigree check

### ISSUE THREAD

**Issue by xiamaz** [LaborBerlin/hum-dragen-routine#28]
- [ ] include all LB-IDs in batch
- [ ] add list of single genomes
- [ ] include info on families
- [ ] include result of automated rules
- [ ] send report to defined receiver

**Comment by your-highness** [comment]
Dear @xiamaz ,

_Can you please elaborate what should be done here? Is this related to #23 and #35?_

Please edit the issue text

**Comment by xiamaz** [comment]
Implemented in https://github.com/xiamaz/pel-transfer-tn via implementation of validation rules
