### ISSUE TITLE
HUM: Consider CRAM instead of BAM compression for WGS alignment files

### ISSUE THREAD

**Issue by AxelMacFoly** [LaborBerlin/hum-dragen-routine#31]
**Background:** 
Reduction of the archive footprint is always important. So far alignment files in BAM format for archived. A new benchmark revealed that the compression rate can be increased by 66% for WGS data sets.

**Compression comparison table**
WGS BAM file name| BAM size [byte] | CRAM size [byte] | Reduction to
-- | -- | -- | --
LB22_2912_dragen | 70.125.776.062 | 21.477.199.295 | 31%
LB22_2913_dragen | 74.630.305.453 | 23.153.417.024 | 31%
LB22_2914_dragen | 67.576.292.017 | 20.008.966.275 | 30%
LB22_2969_dragen | 82.155.244.563 | 25.202.427.329 | 31%
LB22_2970_dragen | 60.541.492.904 | 18.075.535.453 | 30%
LB22_2971_dragen | 65.799.102.034 | 19.049.112.600 | 29%
LB22_3026_dragen | 62.039.797.420 | 18.081.498.903 | 29%
LB22_3027_dragen | 59.522.497.824 | 17.384.519.590 | 29%
LB22_3028_dragen | 38.418.807.588 | 10.803.164.804 | 28%
LB22_3029_dragen | 60.388.808.402 | 17.611.554.798 | 29%
LB22_3030_dragen | 51.866.584.520 | 14.737.622.518 | 28%
LB22_3031_dragen | 61.989.436.200 | 18.075.602.328 | 29%
LB22_3097_dragen | 54.829.528.816 | 15.905.992.563 | 29%
LB22_3271_dragen | 58.975.345.492 | 17.182.908.068 | 29%
LB22_3272_dragen | 65.349.746.344 | 18.871.874.298 | 29%
LB22_3273_dragen | 69.548.704.305 | 20.416.929.499 | 29%
LB22_3274_dragen | 52.982.163.672 | 15.150.622.174 | 29%
LB22_3275_dragen | 57.665.703.161 | 16.806.392.729 | 29%
LB22_3276_dragen | 56.666.651.732 | 16.364.354.355 | 29%
LB22_3283_dragen | 48.461.832.884 | 13.933.837.190 | 29%
  | 1.219.533.821.393 | 358.293.531.793 | 29%

**Comment by xiamaz** [comment]
Thanks, we could switch the entire DRAGEN process to CRAM, but we will need to check whether BIH is fine with CRAM. Otherwise this can be changed for storage purposes in LB, but will need an additional conversion step, potentially when moving the data.

**Comment by your-highness** [comment]
Primarily this would be useful to reduce the data throughput when transferring data to CUBI. 

We need to discuss this with stakeholders at CUBI because no alignment or read data will be stored at LB.

**Comment by xiamaz** [comment]
M. Holtgrewe: Concerns, a lot of tools don't know CRAM, reference needs to be matched 100%. Does not want CRAM
