### ISSUE TITLE
Generate Filtered Single VCF of Index for Second-look purposes

### ISSUE THREAD

**Issue by xiamaz** [LaborBerlin/hum-dragen-routine#34]

**Comment by your-highness** [comment]
Dear @xiamaz ,

Can you please explain which filters need to be applied? As I see it the single VCFs is already present in SODAR.

**Comment by xiamaz** [comment]
We need to filter by Agilent V8 BED +50bp. This is currently still needed, as our current SOP still requires a second-look using MutationDistiller and it would be impractical to have to upload the entire WGS vcf

**Comment by xiamaz** [comment]
@your-highness All the single VCF have now been generated. They are inside each individual batch in a vcf file ending with `.exom-v8.hard-filtered.vcf.gz`

**Comment by your-highness** [comment]
It's not working with GNU parallel correctly now.
