### ISSUE TITLE
Pedigree: `pelextract/generated_ped.sh` should also consider data entries for 2023

### ISSUE THREAD

**Issue by your-highness** [LaborBerlin/hum-dragen-routine#41]
**Background:**
In 2023 a new table will be used. Include this in batch PED retrieval.

**Tasks:**
- [ ] Run `./pelextract/batcher.py` also for new data table. See:
   https://github.com/LaborBerlin/hum-dragen-routine/blob/8f33be110017677aac270c4b4a1a1f30eee1ec8a/pelextract/generate_peds.sh#L9-L11

**References:**
#25

**Comment by xiamaz** [comment]
Solved in https://github.com/xiamaz/pel-transfer-tn
