### ISSUE TITLE
Reenable repeat expansion calling

### ISSUE THREAD

**Issue by xiamaz** [LaborBerlin/hum-dragen-routine#49]
repeat expansion calling had been disabled because of issues with downsampled data. Since we don't downsample data anymore it should be fine to reenable the option.

- [x] Enable the option for repeat expansion calling and check that processing still works
- [ ] compute repeat expansions for previous batches

Since repeat expansions are currently not supported by varfish for visualization, the second task has lower priority.

**Comment by your-highness** [comment]
It worked correctly for DRAGEN v3.10. We had to disable it after upgrade to v4. Since we have v3.10 fixed now, it can be safely enabled.

A recomputation is not part of the routine dev and will be discussed later.
